/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:bec18154-6a92-485c-bf04-a93ae1f7f578",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_XMbwIILIw",
    "aws_user_pools_web_client_id": "n457mmqsdvi5la2nir9vnb5ps",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "eu-west-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "PlayerDB-develop",
            "region": "eu-west-1"
        },
        {
            "tableName": "LeaguesDB-develop",
            "region": "eu-west-1"
        },
        {
            "tableName": "LeaguePlayerDB-develop",
            "region": "eu-west-1"
        },
        {
            "tableName": "PlStandingsDB-develop",
            "region": "eu-west-1"
        },
        {
            "tableName": "PlTeamsDB-develop",
            "region": "eu-west-1"
        },
        {
            "tableName": "PLResultsDB-develop",
            "region": "eu-west-1"
        },
        {
            "tableName": "PLFixturesDB-develop",
            "region": "eu-west-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "LastManStandingAPI",
            "endpoint": "https://ida5es25ne.execute-api.eu-west-1.amazonaws.com/develop",
            "region": "eu-west-1"
        }
    ]
};


export default awsmobile;
